### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Ahrimdon** [V3nilla/H2M-MOD-Torrent-File#1]
bro dis shit has like half the files missing and is broken as fuck my boy

**Comment by V3nilla** [comment]
> bro dis shit has like half the files missing and is broken as fuck my boy

All files download directly from leak twitter post. All files exists, except MW2 Campaign map files

**Comment by iamse7en** [comment]
I already have the game on Steam. Do I need multiplayer portion only? I don't need the bigger Single Player Campaign portion right?
