### ISSUE TITLE
New master server exe

### ISSUE THREAD

**Issue by richard-hendrixx** [V3nilla/H2M-MOD-Torrent-File#2]
New edited exe with new master server [h2m-revived.zip](https://github.com/user-attachments/files/16642355/h2m-revived.zip)
This works for both game and server and will list in ingame server list

**Comment by V3nilla** [comment]
Already uploaded in "Working Server List" folder

**Comment by rebelancap** [comment]
How do you stop Win11 antivirus from deleting `h2m-mod.exe`? It's relentless. 

Edit: Windows Defender > Protection History > Restore the file and then allow it

**Comment by V3nilla** [comment]
> How do you stop Win11 antivirus from deleting `h2m-mod.exe`? It's relentless.
> 
> Edit: Windows Defender > Protection History > Restore the file and then allow it

Its better to fully disable Windows Defender. The worst antivirus i ever seen
