### ISSUE TITLE
should only downlaod H1 + H2M???

### ISSUE THREAD

**Issue by shzdiushju** [V3nilla/H2M-MOD-Torrent-File#3]
am a bit confused... so if i get the H1 + H2M by lxstwxrden, do i still need to install MW2 CAMPAIGN REMASTERED MAPS and H1 DLCS and h2m-usermaps in the H1 + H2M by lxstwxrden files as well???? or h1 + h2 is enough? i would appreciate an answer

**Comment by V3nilla** [comment]
Yes, you still need to download MW2 Campaign Remastered Maps if you get H1 + H2M by lxstwxrden, other torrents aren't needed
