### ISSUE TITLE
Open console.exe launching and quitting very fast all day long

### ISSUE THREAD

**Issue by rebelancap** [V3nilla/H2M-MOD-Torrent-File#4]
Ever since I tried installing this mod, my Windows is acting strange. I deleted everything related to the base game and mod too. Every 10 seconds, I get a window that launches and immediately closes, every 10 seconds. It's so fast, you really only see a border of a window. I watched sysinternals process explorer and task manager like a hawk and found it's `OpenConsole.exe`. But that is a generic command prompt - I don't know what's executing, I can't make it stop. It's very annoying; I can't even game anymore because it makes my current app lose focus, even shows the taskbar on Fullscreen games. Please help. Worried I have some malware or virus. 

Rebooting did nothing, did dsim health check, system file checker, etc. Reboot, still getting it every 8-10 seconds.

**Comment by V3nilla** [comment]
> Ever since I tried installing this mod, my Windows is acting strange. I deleted everything related to the base game and mod too. Every 10 seconds, I get a window that launches and immediately closes, every 10 seconds. It's so fast, you really only see a border of a window. I watched sysinternals process explorer and task manager like a hawk and found it's `OpenConsole.exe`. But that is a generic command prompt - I don't know what's executing, I can't make it stop. It's very annoying; I can't even game anymore because it makes my current app lose focus, even shows the taskbar on Fullscreen games. Please help. Worried I have some malware or virus.
> 
> Rebooting did nothing, did dsim health check, system file checker, etc. Reboot, still getting it every 8-10 seconds.

Hi. It's really weird that this started. I've been using all these files since they leaked online, and nothing has happened to my computer. Did you install anything else before installing the client specifically downloaded from my github? For example - Modern Warfare Remastered repack or something else. Because I have never seen a file called OpenConsole.exe. Contact me on discord, I will try to help you. And yes, by the way, if you have a SHA-256 hash of this file, post it here, I'll try to find out what this file really is.

**Comment by rebelancap** [comment]
I own steam version of base game, so I did mod only. It only started happening around this time I was installing the base game and mod. But I discovered it. Starting process of elimination with task manager. Found two tasks "Zoom Meetings" pointing to `C:\ProgramData\Mds-Software` (I don't have Zoom installed). Ended those tasks, and the cmd pop ups stopped immediately. Inside the folder was a `blank f1.txt` and `nddm.exe`. Deleted the folder, and the Load regedit trying to open `nddm.exe` at startup. Very strange, but I can't know for sure it was the mod that caused it!

Thanks for the offer to help! Glad I figured it out.

**Comment by V3nilla** [comment]
> I own steam version of base game, so I did mod only. It only started happening around this time I was installing the base game and mod. But I discovered it. Starting process of elimination with task manager. Found two tasks "Zoom Meetings" pointing to `C:\ProgramData\Mds-Software` (I don't have Zoom installed). Ended those tasks, and the cmd pop ups stopped immediately. Inside the folder was a `blank f1.txt` and `nddm.exe`. Deleted the folder, and the Load regedit trying to open `nddm.exe` at startup. Very strange, but I can't know for sure it was the mod that caused it!
> 
> Thanks for the offer to help! Glad I figured it out.

This has 100% nothing to do with the mod. I've now checked for these file folders, and I also found nothing. I reread your text, and noticed that this started happening when you were still installing the mod, not just after launching it. So it's definitely 100% unrelated to the mod
